Snapshot state for reorg containers
increase timeout

uncomment other stuff

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -43,9 +43,9 @@ commands:
             sleep 4m
             # wait until we're UP
             for i in {1..60}; do
-              if [ "$(curl localhost:8000/contracts)" ]; then 
+              if [ "$(curl localhost:8000/contracts)" ]; then
                 break
-              fi; 
+              fi;
               sleep 1
             done
             # stop geth in docker so that we can snapshot
@@ -63,7 +63,80 @@ commands:
             done
             sudo tar czf ${TAR_NAME} data/geth plasma-contracts/contracts/ plasma-contracts/build/* ../tester/CONTRACT_SHA
             export BOTO_CONFIG=/dev/null
-            gsutil cp ${TAR_NAME} gs://circleci-docker-artifacts 
+            gsutil cp ${TAR_NAME} gs://circleci-docker-artifacts
+            echo "https://storage.googleapis.com/circleci-docker-artifacts/${TAR_NAME}"
+            PLASMA_CONTRACTS=$(curl localhost:8000/contracts)
+            DATA=$(echo "Contracts snapshotted with MIN_EXIT_PERIOD for SHA ( ${CONTRACT_SHA} ): << parameters.min_exit_period >>.\r\n Snapshot located at: \r\n   https://storage.googleapis.com/circleci-docker-artifacts/${TAR_NAME}  \r\n  Contract addresses: \r\n ${PLASMA_CONTRACTS} " | jq -Rs '.')
+            if [ "$CIRCLE_BRANCH" = "master" ]; then
+              # append the data you would usually post as a comment to a file and create a release out of this file
+              echo ${DATA} >> /tmp/release
+              echo $'\r\n\r\n\r\n' >> /tmp/release
+            else
+              curl -H "Authorization: token ${GITHUB_TOKEN}" -X POST -d "{\"body\": ${DATA} }" "https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/issues/${CIRCLE_PULL_REQUEST##*/}/comments"
+            fi
+            ls data/geth
+            docker-compose down && sudo rm -rf data/geth/chaindata data/geth/LOCK data/geth/lightchaindata data/geth/nodekey data/geth/nodes data/geth/transactions.rlp
+
+  snapshot_reorg:
+    description: Deploy contracts to Geth via docker-compose with parametrized MIN_EXIT_PERIOD and expose addresses and snapshot URL
+    parameters:
+      min_exit_period:
+        type: integer
+        description: "The value used for plasma contracts deployment"
+    steps:
+      - run:
+          name: Get Plasma Deployer image and standup geth and deploy contracts
+          no_output_timeout: 40m
+          command: |
+            set -xe
+            IMAGE_NAME=elixir-omg-tester-plasma-deployer
+            if [ "$CIRCLE_BRANCH" = "master" ]; then
+              IMAGE_DATE="$(date -u +%Y%m%d)"
+              TAG="$IMAGE_NAME:stable-$IMAGE_DATE"
+            else
+              IMAGE_GIT=$(git rev-parse --short HEAD)
+              TAG="$IMAGE_NAME:dev-$IMAGE_GIT"
+            fi
+            cd contracts_reorg/
+            CONTRACT_SHA=$(cat ../tester/CONTRACT_SHA)
+            MIN_EXIT_PERIOD=<< parameters.min_exit_period >> IMAGE=${TAG} docker-compose up -d
+            timeout 25m docker-compose logs --follow || true
+
+            ### in the mean time, install gcloud requirements
+            wget https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-272.0.0-linux-x86_64.tar.gz -O gcloud-sdk.tar.gz
+            tar zxf gcloud-sdk.tar.gz google-cloud-sdk
+            mv google-cloud-sdk ~/.google-cloud-sdk
+            ~/.google-cloud-sdk/install.sh --quiet
+            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
+            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
+            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
+            ### done installing gcloud requirements
+            ### cleanup
+            rm -rf ~/.google-cloud-sdk
+            # wait until we're UP
+            for i in {1..60}; do
+              if [ "$(curl localhost:8000/contracts)" ]; then
+                break
+              fi;
+              sleep 1
+            done
+            # stop geth in docker so that we can snapshot
+            docker exec -it $(docker ps -aqf "name=node-1") /bin/sh -c "pkill -INT geth"
+            # ipc is not for cp
+            sudo rm -f data/geth.ipc
+            sudo rm -f data/geth/nodekey
+            TAR_NAME=$(echo data-${TAG}-MIN_EXIT_PERIOD-<< parameters.min_exit_period >>-PLASMA_CONTRACTS_SHA-${CONTRACT_SHA}-reorg.tar.gz | sed 's/:/-/')
+            echo ${TAR_NAME}
+            # for every key in object db.json create a file
+            # where the key is the name of the file and the content of the file is it's value
+            # for example plasma-contracts/build/authority_address file has content 0xc0f780dfc35075979b0def588d999225b7ecc56f
+            KEYS=($(cat plasma-contracts/build/db.json | jq -r '.contracts' | jq 'keys[]' | tr -d '"'))
+            for i in "${!KEYS[@]}"; do
+              echo $(cat plasma-contracts/build/db.json | jq -r '.contracts' | jq -r '.'${KEYS[i]} | tr -d '"') > plasma-contracts/build/"${KEYS[i]}"
+            done
+            sudo tar czf ${TAR_NAME} data/geth ethash/ plasma-contracts/contracts/ plasma-contracts/build/* ../tester/CONTRACT_SHA
+            export BOTO_CONFIG=/dev/null
+            gsutil cp ${TAR_NAME} gs://circleci-docker-artifacts
             echo "https://storage.googleapis.com/circleci-docker-artifacts/${TAR_NAME}"
             PLASMA_CONTRACTS=$(curl localhost:8000/contracts)
             DATA=$(echo "Contracts snapshotted with MIN_EXIT_PERIOD for SHA ( ${CONTRACT_SHA} ): << parameters.min_exit_period >>.\r\n Snapshot located at: \r\n   https://storage.googleapis.com/circleci-docker-artifacts/${TAR_NAME}  \r\n  Contract addresses: \r\n ${PLASMA_CONTRACTS} " | jq -Rs '.')
@@ -412,7 +485,7 @@ jobs:
           min_exit_period: 120
       - snapshot:
           min_exit_period: 240
-      - run: 
+      - run:
           name: Gather all the snapshots and publish a release
           command: |
             if [ "$CIRCLE_BRANCH" = "master" ]; then
@@ -420,13 +493,32 @@ jobs:
               IMAGE_DATE="$(date -u +%Y%m%d)"
               TAG="plasma-contracts-snapshot-$IMAGE_DATE-${CONTRACT_SHA}"
               echo ${TAG}
-              DATA=$(cat /tmp/release | jq -Rs '.')              
+              DATA=$(cat /tmp/release | jq -Rs '.')
               echo ${DATA}
               curl -H "Authorization: token ${GITHUB_TOKEN}" -X POST -d "{\"tag_name\": \"${TAG}\",\"body\": ${DATA} }" "https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/releases"
             fi
-            
-          
-    
+
+  snapshot_plasma_contracts_reorg:
+    machine:
+      image: ubuntu-1604:201903-01
+    steps:
+      - checkout
+      - attach_workspace: *attach_workspace
+      - snapshot_reorg:
+          min_exit_period: 120
+      - run:
+          name: Gather all the snapshots and publish a release
+          command: |
+            if [ "$CIRCLE_BRANCH" = "master" ]; then
+              CONTRACT_SHA=$(cat tester/CONTRACT_SHA)
+              IMAGE_DATE="$(date -u +%Y%m%d)"
+              TAG="plasma-contracts-snapshot-reorg-$IMAGE_DATE-${CONTRACT_SHA}"
+              echo ${TAG}
+              DATA=$(cat /tmp/release | jq -Rs '.')
+              echo ${DATA}
+              curl -H "Authorization: token ${GITHUB_TOKEN}" -X POST -d "{\"tag_name\": \"${TAG}\",\"body\": ${DATA} }" "https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/releases"
+            fi
+
 
 workflows:
   version: 2
@@ -475,8 +567,12 @@ workflows:
       - publish_plasma_deployer:
           requires:
             - build_tester_plasma_deployer
-      
+
       - snapshot_plasma_contracts:
+          requires:
+            - publish_plasma_deployer
+
+      - snapshot_plasma_contracts_reorg:
           requires:
             - publish_plasma_deployer
 
